### ISSUE TITLE
As a user I want to be dealt a hand so I can play a round

### ISSUE THREAD

**Issue by randomcodenz** [randomcodenz/canasta#1]
**Acceptance criteria**
- The deck must be shuffled before dealing so the cards are random
- Each player must be dealt 15 cards

**Tasks**
- [x] Create basic rails application
- [x] Create simple home page
- [x] Add button to home page to create a new game
- [x] Create new game with 2 default players
- [x] Start a new round
- [x] Create a new deck
- [x] Shuffle the deck
- [x] Deal 15 cards to each player
- [x] Create the discard pile from the top card of the remaining stock
- [x] Display each players hand
- [x] Display the discard pile
- [x] Display the stock
