### ISSUE TITLE
Pick up the discard pile

### ISSUE THREAD

**Issue by randomcodenz** [randomcodenz/canasta#14]
Allow a player to pick up the discard pile.

Contains:
- [ ] #11 As a player I want to pick up the discard pile ...
- [ ] #12 As a player I want to see when the discard pile is frozen ...
- [ ] #13 As a player I want to pick up a frozen discard pile ...
