### ISSUE TITLE
Initial Melds

### ISSUE THREAD

**Issue by randomcodenz** [randomcodenz/canasta#20]
Add initial meld limits into the game.

Contains:
- [ ] #17 As a player I want to see my initial meld requirements ...
- [ ] #18 As a player I want to be able to prepare 1 or more melds in my hand ...
- [ ] #19 As a player I want to see the potential score of my planned melds ...
