### ISSUE TITLE
Red 3s

### ISSUE THREAD

**Issue by randomcodenz** [randomcodenz/canasta#26]
Handle red 3s correctly.

Contains:
- [ ] #21 As a player I want any red 3s in my hand placed face up on the table ...
- [ ] #22 As a player I want any red 3s dealt to me to be replaced from stock ...
- [ ] #23 As a player I want any red 3s I draw to be replaced from stock ...
- [ ] #24 As a player when I draw a red 3 from stock as the last card I want the round to end ...
- [ ] #25 As a player I want any red 3s I have tabled to be included in my score
