### ISSUE TITLE
Play a single round

### ISSUE THREAD

**Issue by randomcodenz** [randomcodenz/canasta#7]
Allow 2 players to play a single round.

Contains:
- [x] #1 As a user I want to be dealt a hand ...
- [x] #2 As a user I want to play a turn ...
- [x] #3 As a player I want to table a meld ...
- [x] #4 As a player I want to add cards to a meld I have already tabled ...
- [x] #5 As a player I want the round to end when the stock has been exhausted ...
- [x] #6 As a player I want to see my score when the round ends ...
